### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by hominlinx** [whtsky/iEditor#1]
请问您的这个在线编辑如何使用啊

**Comment by whtsky** [comment]
http://whouz.com/2013-01-30-simple-online-editor.html

没有保存功能，只是玩具而已……

**Comment by hominlinx** [comment]
你的这个文档我看了 能通过什么方式联系上你啊？我也是山东的，想问问你几个问题 可否？

**Comment by whtsky** [comment]
发邮件就好了，手机有推送，看到就会回的
whtsky#gmail
